### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by lizhong8532** [zont/gulp-usemin#114]
## I use gulp-usemin, if use any option like that
```
gulp.src('src/*.html')
		.pipe($.usemin({
			vendorCss: [$.minifyCss()]
			themeCss: [$.minifyCss()],
			pageCss: [$.minifyCss(), $.rev()],
			pageCss: [$.rev()]
			graphJs: [$.uglify()],
			pageJs: [$.uglify(), $.rev()]
		}))
.pipe(gulp.dest('dist'));

```

## then will be print error in console

```
Trace
    at Stream.addListener (events.js:179:15)
    at Stream.pipe (stream.js:118:10)
    at d:\mmdb\graph\apache-tomcat-7.0.56\webapps\ROOT\node_modules\gulp-usemin\lib\pipeline.js:26:27
    at Array.forEach (native)
    at module.exports (d:\mmdb\graph\apache-tomcat-7.0.56\webapps\ROOT\node_modules\gulp-usemin\lib\pipeline.js:25:9)
    at d:\mmdb\graph\apache-tomcat-7.0.56\webapps\ROOT\node_modules\gulp-usemin\lib\htmlBuilder.js:35:9
    at Function.promise (d:\mmdb\graph\apache-tomcat-7.0.56\webapps\ROOT\node_modules\gulp-usemin\node_modules\q\q.js:642:9)
    at d:\mmdb\graph\apache-tomcat-7.0.56\webapps\ROOT\node_modules\gulp-usemin\lib\htmlBuilder.js:21:14
    at Array.map (native)
    at module.exports (d:\mmdb\graph\apache-tomcat-7.0.56\webapps\ROOT\node_modules\gulp-usemin\lib\htmlBuilder.js:20:25)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.

....
```

## but remove all option then build successfully, I try alone run option's each task resulted is successfully

```
gulp.src('src/*.html')
		.pipe($.usemin())
.pipe(gulp.dest('dist'));

```

## current environment
node v0.12.2
minify-css v1.0.0
uglify v1.1.0
rev v2.0.1

## Who help me, thanks every everyone

**Comment by calledT** [comment]
just find you miss comma , it should be

```js
gulp.src('src/*.html')
        .pipe($.usemin({
            vendorCss: [$.minifyCss()],
            themeCss: [$.minifyCss()],
            pageCss: [$.minifyCss(), $.rev()],
            pageCss: [$.rev()],
            graphJs: [$.uglify()],
            pageJs: [$.uglify(), $.rev()]
        }))
.pipe(gulp.dest('dist'));
```

look carefully

**Comment by zont** [comment]
Cannot reproduce.
Please check on version 0.3.14
