### ISSUE TITLE
Multiple HTML files

### ISSUE THREAD

**Issue by mission-accepted** [zont/gulp-usemin#119]
Hi there.

My gulp task looks like this:
````
gulp.task('build-html', function () {
  return gulp.src(['./*.html'])
    .pipe(plugins.usemin({
      css: [plugins.minifyCss(), 'concat'],
      html: [plugins.minifyHtml({empty: true})],
      js: [plugins.uglify({
        mangle: false,
        compress: false,
        beautify: true
      }), plugins.rev()]
    }))
    .pipe(gulp.dest(paths.server));
});
````

I have to files matching the regexp: `slave.html` and `master.html`. I want to apply `usemin`to both of them. 

But unfortunately I get the following error when running my task:

````
stream.js:94
      throw er; / Unhandled stream error in pipe.
            ^
Error: write after end
    at writeAfterEnd (/Users/path/to/development/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:144:12)
    at DestroyableTransform.Writable.write (/Users/path/to/development/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:192:5)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)
    at Stream.endStream (/Users/path/to/development/node_modules/gulp-usemin/node_modules/gulp-concat/index.js:90:10)
    at _end (/Users/path/to/development/node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/path/to/development/node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:74:5)
    at Transform.onend (/Users/path/to/development/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:199:16)
    at Transform.emit (events.js:129:20)
/
````

Both files access some same files. If I run the same task but replace the `./*.html` selector by `./master.html` or `./slave.html` everything works like expected and the correct file is generated. 

Any ideas what I am missing?
Thanks!

**Comment by jpdesigndev** [comment]
@mission-accepted Were you able to figure this out?

**Comment by doubaokun** [comment]
Same question.

**Comment by Sirlon** [comment]
I was able to resolve that error by defining each task as a function and return the stream object.
```javascript
.pipe($.usemin({
        js: [() => $.uglify(), 'concat'],
        css: [() => $.minifyCss(), 'concat']
}))
```
