### ISSUE TITLE
Usemin fails with "Error: write after end" when used in watcher

### ISSUE THREAD

**Issue by leehambley** [zont/gulp-usemin#153]
``` js
var useminPipe = lazypipe()
.pipe(usemin, {
  css: [function(){return rev}],
  js: [function(){return (options.minifyScripts ? uglify : gutil.noop)}, function(){return rev}],
  html: [replace(/\$\$harrowEnv\$\$/g, options.harrowEnv), preprocess(), (options.minifyHTML ? htmlmin({collapseWhitespace: true}) : gutil.noop())],
})
.pipe(debug, { title: "usemin" })
gulp.task('html:usemin', ['html:templates', 'html:wiredep', 'scripts', 'styles', 'images', 'fonts'], () => {
  return gulp.src(useminPaths.src)
  .pipe(useminPipe())
  .pipe(gulp.dest(useminPaths.dest));
});
gulp.task('watch', ['all'], () => {
  gulp.watch([templatesPaths.src, useminPaths.src], ['html'])
});
```
I believe this is wired up correctly, and I read the "if you need to use a pipeline more than once, use functions" then the watcher simply drops out, and never completes. I need some pointers please. Happy to provide more info if you need it.

```
[12:15:07] usemin styles/main-ac5e62cbdf.css                                                     [6/1821]│" Press ? for help             |    <link rel="icon" type="image/svg+xml" href="/images/logo-c-primary-d»
[12:15:07] usemin scripts/oldieshim-e64a15903a.js                                                        │                               |    <link rel="icon" type="image/x-icon"  href="/images/logo-c-primary-d»
[12:15:07] usemin scripts/vendor-2b7168422f.js                                                           │.. (up a dir)                  |
[12:15:07] usemin scripts/scripts-ea4fe31d85.js                                                          │</harrow/frontend/.tmp/        |    <link rel="stylesheet" href="styles/vendor-fd2aaca893.css"/>
stream.js:74                                                                                             │▸ fonts/                       |    <link rel="stylesheet" href="styles/main-ac5e62cbdf.css"/>
      throw er; // Unhandled stream error in pipe.                                                       │▸ images/                      |  </head>
      ^                                                                                                  │▾ scripts/                     |  <body ng-app="harrowApp">
                                                                                                         │  ▾ config/                    |    <!--[if lt IE 7]>
Error: write after end                                                                                   │      constants.js             |      <p class="browsehappy">You are using an <strong>outdated</strong> »
  at writeAfterEnd (frontend/node_modules/readable-stream/lib/_stream_w│      en_GB.js                 |    <![endif]-->
ritable.js:198:12)                                                                                       │      scroll_to_top.js         |
  at Transform.Writable.write (frontend/node_modules/readable-stream/li│      translate.js             |    <p translate="misc.verbs.edit">Hello World</p>
b/_stream_writable.js:243:5)                                                                             │  ▸ controllers/               |
  at Stream.ondata (stream.js:31:26)                                                                     │  ▸ directives/                |    <section id="app">
  at emitOne (events.js:77:13)                                                                           │  ▸ filters/                   |      <div flash-alert="success" active-class="flashAlert flashAlert_vis»
  at Stream.emit (events.js:169:7)                                                                       │  ▸ resources/                 |        <span>{{flash.message}}</span>
  at Stream.endStream (frontend/node_modules/gulp-concat/index.js:90:10│  ▸ services/                  |      </div>
)
```

**Comment by leehambley** [comment]
Edit, I strongly, strongly suspect that because watch reuses the lazypipe twice, I have to reset it somehow, but I have no idea how to do it?

**Comment by leehambley** [comment]
For anyone else running into this `gulp-replace()` and `gulp-util.noop()` both close the stream, my fix:

``` diff
diff --git a/Gulpfile.babel.js b/Gulpfile.babel.js
index 5840c08..3409a14 100644
--- a/Gulpfile.babel.js
+++ b/Gulpfile.babel.js
@@ -129,8 +129,14 @@ var wiredepPipe = lazypipe()
 var useminPipe = lazypipe()
 .pipe(usemin, {
   css: [rev],
-  js: [(options.minifyScripts ? uglify : gutil.noop), rev],
-  html: [replace(/\$\$harrowEnv\$\$/g, options.harrowEnv), preprocess(), (options.minifyHTML ? htmlmin({collapseWhitespace: true}) : gutil.noop())],
+  js: [
+    (options.minifyScripts ? uglify : gutil.noop),
+    rev
+  ],
+  html: [
+    function(){ return replace(/\$\$harrowEnv\$\$/g, options.harrowEnv)},
+    (options.minifyHTML ? htmlmin({collapseWhitespace: true}) : function() { return gutil.noop() })
+  ],
 })
 .pipe(debug, { title: "usemin" })
```
