### ISSUE TITLE
Unhandled stream error in pipe

### ISSUE THREAD

**Issue by ilovecoffee** [zont/gulp-usemin#165]
I am encountering following issue:

`
$ gulp build
[13:17:56] Using gulpfile ~/Projects/projectx/gulpfile.js
[13:17:56] Starting 'build'...
[13:17:56] Starting 'build-clean-dist'...
[13:17:56] Starting 'build-clean-temp'...
[13:17:56] Starting 'jshint'...
[13:17:56] Starting 'sass'...
[13:17:56] Finished 'build-clean-dist' after 32 ms
[13:17:56] Finished 'sass' after 451 ms
[13:17:56] Finished 'build-clean-temp' after 489 ms
[13:17:59] Finished 'jshint' after 3.58 s
[13:17:59] Starting 'build-copy'...
[13:18:00] Finished 'build-copy' after 368 ms
[13:18:00] Starting 'build-iife'...
[13:18:00] Finished 'build-iife' after 202 ms
[13:18:00] Starting 'build-usemin'...

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/coffeebeans/Projects/projectx/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/Users/coffeebeans/Projects/projectx/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/Users/coffeebeans/Projects/projectx/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2026:9)
    at token_error (eval at <anonymous> (/Users/coffeebeans/Projects/projectx/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2034:9)
    at unexpected (eval at <anonymous> (/Users/coffeebeans/Projects/projectx/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2040:9)
    at expr_atom (eval at <anonymous> (/Users/coffeebeans/Projects/projectx/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2542:13)
    at maybe_unary (eval at <anonymous> (/Users/coffeebeans/Projects/projectx/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2716:19)
    at expr_ops (eval at <anonymous> (/Users/coffeebeans/Projects/projectx/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2751:24)
    at maybe_conditional (eval at <anonymous> (/Users/coffeebeans/Projects/projectx/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2756:20)
    at maybe_assign (eval at <anonymous> (/Users/coffeebeans/Projects/projectx/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2780:20)
`

Installed packages in the proect directory:
`
$ npm ls --depth=0
projectx
├── browser-sync@2.11.1
├── git-rev@0.2.1
├── gulp@3.9.1
├── gulp-autoprefixer@3.1.0
├── gulp-clean@0.3.1
├── gulp-iife@0.2.4
├── gulp-jshint@2.0.0
├── gulp-minify-css@1.2.4
├── gulp-rev@7.0.0
├── gulp-sass@2.2.0
├── gulp-uglify@1.5.3
├── gulp-usemin@0.3.21
├── gulp-zip@3.2.0
├── jshint@2.9.1
├── jshint-stylish@2.1.0
├── run-sequence@1.1.5
└── vinyl-ftp@0.4.5
`

My package.json has:

`
$ cat package.json 
{
  "name": "projectx",
  "version": "2.0.0",
  "license": "UNLICENSED",
  "repository": {
    "type": "git",
    "url": "xxx"
  },
  "devDependencies": {
    "browser-sync": "^2.11.1",
    "git-rev": "^0.2.1",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-clean": "^0.3.1",
    "gulp-iife": "^0.2.4",
    "gulp-jshint": "^2.0.0",
    "gulp-minify-css": "^1.2.4",
    "gulp-rev": "^7.0.0",
    "gulp-sass": "^2.2.0",
    "gulp-uglify": "^1.5.3",
    "gulp-usemin": "^0.3.21",
    "gulp-zip": "^3.2.0",
    "jshint": "^2.9.1",
    "jshint-stylish": "^2.1.0",
    "run-sequence": "^1.1.5",
    "vinyl-ftp": "^0.4.5"
  }
}
`

Package installed globally
`
$ npm ls -g --depth=0
/usr/local/lib
├── bower@1.7.7
├── ember-cli@2.3.0
├── gulp@3.9.1
├── npm@3.6.0
└── sass-lint@1.5.0
`

**Comment by ilovecoffee** [comment]
Argh not sure why formatting is messing up.

**Comment by ilovecoffee** [comment]
After digging for some time, I stumbled upon the code that is responsible for this error. If you have a `this._super(...arguments);` line in your function, usemin throws this error.
