### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by hyperbrave** [zont/gulp-usemin#168]
Trying to use this package with the most basic of use cases, and am getting the following error.  It appears section[4] is undefined.

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1253:7)
    at module.exports (node_modules/gulp-usemin/lib/blocksBuilder.js:102:26)

**Comment by hyperbrave** [comment]
the issue was not declaring a path param in the comment block
