### ISSUE TITLE
Error: Cannot find module 'Q'

### ISSUE THREAD

**Issue by asm0dey** [zont/gulp-usemin#87]
Hello!

I down't know why, but I'm getting such error while building:
```
Error: Cannot find module 'Q'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/home/finkel/work_sunrise/repos/smev_admin_panel/controller/src/main/webapp/node_modules/gulp-usemin/lib/htmlBuilder.js:4:11)
    at Transform._transform (/home/finkel/work_sunrise/repos/smev_admin_panel/controller/src/main/webapp/node_modules/gulp-usemin/index.js:17:9)
    at Transform._read (/home/finkel/work_sunrise/repos/smev_admin_panel/controller/src/main/webapp/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/finkel/work_sunrise/repos/smev_admin_panel/controller/src/main/webapp/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/finkel/work_sunrise/repos/smev_admin_panel/controller/src/main/webapp/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/finkel/work_sunrise/repos/smev_admin_panel/controller/src/main/webapp/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
```

It can be easily fixed by changing   
```var Q = require('Q');```
to 
``` var Q = require('q');```
but I'm not sure if it's real fix

Some info about my setup:
```
$ node -v
v0.10.25
$ npm -v
2.1.16
$ gulp -v
[21:16:59] CLI version 3.8.10
[21:16:59] Local version 3.8.10
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.10
DISTRIB_CODENAME=utopic
DISTRIB_DESCRIPTION="Ubuntu 14.10"
$ uname -a
Linux finkel-laptop 3.16.0-29-generic #39-Ubuntu SMP Mon Dec 15 22:27:29 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jhickey** [comment]
Looks like there's a pr in for this now: https://github.com/zont/gulp-usemin/pull/86, I too am seeing the same issue as of this afternoon.

**Comment by asm0dey** [comment]
So let's wait for pull request merge :+1:

**Comment by philBrown** [comment]
I'm guessing the maintainer only develops on Windows.

**Comment by kylewelsby** [comment]
I have experienced this on my linux build server.

**Comment by zont** [comment]
Merged
